name: CMWL_Votes
route_prefix: votes
sp_main: fr.CraftMyWebsite.CMWLink.Votes.SP.Main
bg_main: fr.CraftMyWebsite.CMWLink.Votes.BG.Main
vl_main: fr.CraftMyWebsite.CMWLink.Votes.VL.Main
version: 1.0
author: AxelVatan