name: CMWL_News
route_prefix: news
sp_main: fr.CraftMyWebsite.CMWLink.News.SP.Main
bg_main: fr.CraftMyWebsite.CMWLink.News.BG.Main
vl_main: fr.CraftMyWebsite.CMWLink.News.VL.Main
version: 1.0
author: AxelVatan&Teyir