name: CraftMyWebsite_Link
main: fr.CraftMyWebsite.CMWLink.Spigot.SpigotMain
version: 1.0
author: CraftMyWebsite
description: CraftMyWebsite-Link a java plugin for MC servers
commands:
   cmwl:
      description: Commande principale du plugin
      usage: /cmwl
      permission: cmwl.help