name: CMWL_Boutique
route_prefix: boutique
sp_main: fr.CraftMyWebsite.CMWLink.Boutique.SP.Main
bg_main: fr.CraftMyWebsite.CMWLink.Boutique.BG.Main
vl_main: fr.CraftMyWebsite.CMWLink.Boutique.VL.Main
version: 1.0
author: AxelVatan